### ISSUE TITLE
fails to cancel an order

### ISSUE THREAD

**Issue by AndrejLischishin** [dmarienko/Qubx#35]
Using signals from: 
[signals.csv](https://github.com/user-attachments/files/16933164/signals.csv)

and notebook: https://github.com/xLydianSoftware/xincubator/blob/3571e2890309ce5a7bec67951bf73755f2b70ea0/research/liquidations/issue1.ipynb

this issue can be replicated.

**Comment by dmarienko** [comment]
fixed in last commit
