### ISSUE TITLE
Issue in new on_fit/on_event interface

### ISSUE THREAD

**Issue by dmarienko** [dmarienko/Qubx#44]
Here is test for issue: https://github.com/dmarienko/Qubx/blob/qubx0.4.0-issues/tests/qubx/backtester/simulation_test.py

**Comment by yuriy-arabskyy** [comment]
I resolved the issue here https://github.com/dmarienko/Qubx/pull/45
The solution was to skip on_event after calling on_fit in the same loop. Because the subscriptions didn't yet manage to run through warmup.
